### ISSUE TITLE
Split up code block in total_balance.rb

### ISSUE THREAD

**Issue by warriordog** [warriordog/MPH-Client#33]
The total balance tool has a large block of code that should be broken out into a few different functions for readability.

**Comment by n8chz** [comment]
I can't find a file by that name.

**Comment by warriordog** [comment]
@n8chz I may have already done this but never updated the issue.   I haven't worked on this project in more than a year.

**Comment by warriordog** [comment]
Yeah that file is gone.  No need for this issue now
